### ISSUE TITLE
Java 10 Execution Support

### ISSUE THREAD

**Issue by SuperOok** [ScheidtBachmann/statemachine#3]
The tool should run on Java 8 and higher, especially Java 10.

Starting the compiled program gives warnings:
```
WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by com.google.inject.internal.cglib.core.$ReflectUtils$2 (file:/C:/ws/git/statemachine-gitsrv/de.scheidtbachmann.statemachine.parent/de.scheidtbachmann.statemachine.cli/scc.bat) to method java.lang.ClassLoader.defineClass(java.lang.String,byte[],int,int,java.security.ProtectionDomain)
WARNING: Please consider reporting this to the maintainers of com.google.inject.internal.cglib.core.$ReflectUtils$2
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release
Usage: scc [-hV] [COMMAND]
  -h, --help      Show this help message and exit.
  -V, --version   Print version information and exit.
Commands:
  generate  Generate executable code corresponding to the given input file.
  validate  Check the given input file for syntactic and semantic errors and
              problems.
```

**Comment by sailingKieler** [comment]
Siehe https://github.com/google/guice/issues/1133

**Comment by sailingKieler** [comment]
Siehe auch https://github.com/google/guice/issues/1205

**Comment by sailingKieler** [comment]
ich habe jetzt 2 changes an der build config gepusht. Der erste zieht die Guice-Version von 3 auf 4.2.2 hoch. Ich hatte gehofft, dass macht es schon etwas besser und es sah auch kurzzeitig so aus, war aber nicht nachhaltig.

Mit dem 2. change werden jetzt schlicht 2 `.bat`-Files gebaut. Eins für Java 8 (`sccJava8.bat`), und eins für alle weiteren Versionen (`scc.bat`). Letzteres hat die Einstellung `--add-opens java.base/java.lang=ALL-UNNAMED` gesetzt, die Java8 nicht kennt und daher aussteigt.
Falls das erste nicht gebraucht wird, kann das auch schnell wieder entfernt werden.

Damit solltest Du das tool aber zumindest rausgeben können.

**Comment by eNBeWe** [comment]
This has been resolved at some point in the past. The tool should work properly in at least JDK11 and JDK17.
